ci:
  autoupdate_schedule: quarterly
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^data/
      - id: end-of-file-fixer
        exclude: ^data/
      - id: check-docstring-first
        exclude: ^data/
      - id: check-json
        exclude: ^data/
      - id: check-yaml
        exclude: ^data/
      - id: debug-statements
        exclude: ^data/
      - id: mixed-line-ending
        exclude: ^data/

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - "--py38-plus"

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.8
    hooks:
      - id: blackdoc

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.260"
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
